module.exports.mlk_quotes = [
    "I have a dream that one day this nation will rise up and live out the true meaning of its creed: We hold these truths to be self-evident that all men are created equal. I have a dream that my four little children will one day live in a nation where they will not be judged by the color of their skin but by the content of their character. I have a dream today.",
    "The ultimate measure of a man is not where he stands in moments of comfort and convenience, but where he stands at times of challenge and controversy.",
    "Injustice anywhere is a threat to justice everywhere.",
    "The time is always right to do what is right.",
    "I have decided to stick with love. Hate is too great a burden to bear.",
    "Darkness can not drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.",
    "Nothing in the world is more dangerous than sincere ignorance and conscientious stupidity.",
    "There can be no deep disappointment where there is not deep love.",
    "I have a dream that one day this nation will rise up and live out the true meaning of its creed; We hold these truths to be self-evident: that all men are created equal",
    "Morality cannot be legislated, but behavior can be regulated. Judicial decrees may not change the heart, but they can restrain the heartless.",
    "Everybody can be great... because anybody can serve. You don't have to have a college degree to serve. You don't have to make your subject and verb agree to serve. you only need a heart full of grace. a soul generated by love.",
    "He who passively accepts evil is as much involved in it as he who helps to perpetrate it.",
    "Riots are the voices of the unheard.",
    "I must confess that over the past few years I have been gravely disappointed with the white moderate. I have almost reached the regrettable conclusion that the Negro's great stumbling block in his stride toward freedom is not the White Citizen's Counciler or the Ku Klux Klanner, but the white moderate, who is more devoted to 'order' than to justice; who prefers a negative peace which is the absence of tension to a positive peace which is the presence of justice [...]",
];

module.exports.background_images = [
    { obs_name: "pool", command_name: "pool" },
    { obs_name: "tile-gradient", command_name: "tile" },
    { obs_name: "earth stock", command_name: "earth" },
    { obs_name: "duck", command_name: "duck" },
    { obs_name: "universe 1", command_name: "universe" },
    { obs_name: "invisible", command_name: "invisible" },
    { obs_name: "tornado", command_name: "fire" },
    { obs_name: "rainbow", command_name: "rainbow" },
    { obs_name: "static", command_name: "static" },
    { obs_name: "secret", command_name: "secret"},
    { obs_name: "synth", command_name: "synth"}
];

module.exports.backgrounds_help_message = `Possible backgrounds are, pool, tile, earth, duck, universe, invisible, fire, rainbow, static. E.g. !background duck`;

module.exports.green_screen_scene = `green screen effects`

module.exports.green_screen_camera = `GS Basic`

module.exports.hearts_scene = `hearts helper`
